# fly.toml app configuration file generated for 7pp-bot on 2024-08-28T18:33:49+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '7pp-bot'
primary_region = 'syd'
